### ISSUE TITLE
Allow adding commands using the API

### ISSUE THREAD

**Issue by FlorestanII** [leMaik/RpgPlus#12]

**Comment by leMaik** [comment]
The API could be like this:

```lua
rpgplus.command("command", "subcommand", "subsubcommand", function(args1, arg2) {
  -- do something here
  return true
})
```

The list of subcommands may be as long as you want (they are just shorthands for switching over the arguments. The handler function will get all remaining arguments as parameters, this makes some nice Lua-magic possible (i.e. putting some of them in an array, `function(arg1, otherArgs...)`.

**Comment by leMaik** [comment]
Done. :)
Commands can even be overloaded (i.e. register "command subcommand" and "command subcommand subsubcommand" at the same time). You can also register subcommands without registering the root command (i.e. register "command subcommand" but not "command").
Registering a command handler overwrites the old handler, if there was one.
