### ISSUE TITLE
Notify players if a script throws an exception

### ISSUE THREAD

**Issue by FlorestanII** [leMaik/RpgPlus#24]

**Comment by leMaik** [comment]
Using [jPastebin](https://github.com/BrianBB/jPastebin) to push the stacktraces to Pastebin could be very useful, instead of using books or sendings messages.

**Comment by leMaik** [comment]
Implemented but could need some refactoring for the methods to call lua functions safely. Ended up using [pastebin-java-api](https://github.com/rrev/pastebin-java-api).
