### ISSUE TITLE
Playerstorage bugs

### ISSUE THREAD

**Issue by FlorestanII** [leMaik/RpgPlus#54]
`storage.of(event:getPlayer()).get("quests", nil)` return not `nil`, although `quests` not exists for that player.

**Comment by leMaik** [comment]
`storage.of(player).get` works as intended, but I think I found the bug that caused this.

The storage only supports string values and nested tables of strings. Thus, if you unset a storage value (`storage.of(player).set("foo", nil)`), `nil` is converted to the string `"nil"` and then saved. Actually, unsetting values is not implemented at all.
