### ISSUE TITLE
NPE on inventory:hasItems(....)

### ISSUE THREAD

**Issue by FlorestanII** [leMaik/RpgPlus#61]
`inventory:hasItems(player, {type="log", name="Eichenholz"})` throws an exception, if  a 'normal' oak log is in the players inventory (with no special name etc.).

The exception is thrown because the ItemMeta of a item is sometimes null. And in the ItemMatcher.matches(...) is no check for that: for example: https://github.com/leMaik/RpgPlus/blob/master/src/main/java/de/craften/plugins/rpgplus/components/inventory/ItemMatcher.java#L110

**Comment by leMaik** [comment]
This might also be a bug in SkyblockPlus then. :open_mouth: I'll look into this now.

**Comment by FlorestanII** [comment]
Sometimes it is still unchecked:
https://github.com/leMaik/RpgPlus/blob/c4b7a30baf8c547ed6759eb329c92f07a6bdbe96/src/main/java/de/craften/plugins/rpgplus/components/inventory/ItemMatcher.java#L55
or:
https://github.com/leMaik/RpgPlus/blob/c4b7a30baf8c547ed6759eb329c92f07a6bdbe96/src/main/java/de/craften/plugins/rpgplus/components/inventory/ItemMatcher.java#L118
